name: html2pdf
description: |
  Converts HTML files into PDF using chrome-headless-render-pdf
input:
  htmlPath:
    required: true
    default: index.html
  pdfName:
    required: true
    default: output
runs:
  using: docker
  image: Dockerfile
  args:
  - ${{ inputs.htmlPath }}
  - ${{ inputs.pdfName }}
